### ISSUE TITLE
Reinforcement Learning

### ISSUE THREAD

**Issue by fabioseel** [berenslab/retinal-rl#31]
Stuff that needs to be done to make the Reinfocement Learning usable in the new system:
- [x] #36
- [x] #71
  - also: automatic discovery / mapping of NeuralCircuits to Encoder/Core/Decoder ?
- [x] how to implement RNN in Brain system (forward returning additional output RNN states, output shape return value?) [NeuralCircuit Core](https://github.com/berenslab/retinal-rl/tree/master/retinal_rl/models/circuits/latent_core.py), [SFBrain - Init](https://github.com/berenslab/retinal-rl/tree/master/retinal_rl/rl/sample_factory/models.py#L88), [SFBrain - Forward](https://github.com/berenslab/retinal-rl/tree/master/retinal_rl/rl/sample_factory/models.py#L106)
- [x] #33
- [x] #35
- [x] #34
- [ ] delete deprecated code ([analysis](https://github.com/berenslab/retinal-rl/tree/master/retinal_rl/rl/analysis/plot_old.py), [statistics](https://github.com/berenslab/retinal-rl/tree/master/retinal_rl/rl/analysis/statistics.py), ...?)
- [ ] #38

Side-quests:
- [ ] Minimal samplefactory?

Nice-to-have Feature ideas:
- [ ] create a dataset like interface for doom scenarios (with test / train splits ...)
